### ISSUE TITLE
No module named 'datalad_metalad.provider.datasettraverse' (ModuleNotFoundError)

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#207]
I have the latest commit of master installed in a virtual environment (had to `pip install six` additionally...)

Getting this error when running `meta-conduct`.

```
datalad meta-conduct /Users/jsheunis/Documents/psyinf/datalad-catalog/datalad_catalog/scripts/extract_file_metadata.json \
    traverser:"." \
    traverser:file \
    traverser:True \
    extractor:File \
    extractor:metalad_core \
    | jq '.["pipeline_element"]["result"]["metadata"][0]["metadata_record"]' >> testybesty.jsonl

[ERROR] ModuleNotFoundError(No module named 'datalad_metalad.provider.datasettraverse') (ModuleNotFoundError)
```

This has worked before and also on a previous version of metalad (can't recall atm though).

**Comment by jsheunis** [comment]
The version giving the error:

```
- metalad:
    - description: DataLad semantic metadata command suite
    - entrypoints:
      - datalad_metalad.add.Add:
        - class: Add
        - load_error: None
        - module: datalad_metalad.add
        - names:
          - meta-add
          - meta_add
      - datalad_metalad.aggregate.Aggregate:
        - class: Aggregate
        - load_error: None
        - module: datalad_metalad.aggregate
        - names:
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.conduct.Conduct:
        - class: Conduct
        - load_error: None
        - module: datalad_metalad.conduct
        - names:
          - meta-conduct
          - meta_conduct
      - datalad_metalad.dump.Dump:
        - class: Dump
        - load_error: None
        - module: datalad_metalad.dump
        - names:
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract:
        - class: Extract
        - load_error: None
        - module: datalad_metalad.extract
        - names:
          - meta-extract
          - meta_extract
    - load_error: None
    - module: datalad_metalad
    - version: 0.3.0a5+74.g259303f
```

Previous version that works:

```
metalad:
    - description: DataLad semantic metadata command suite
    - entrypoints:
      - datalad_metalad.add.Add:
        - class: Add
        - load_error: None
        - module: datalad_metalad.add
        - names:
          - meta-add
          - meta_add
      - datalad_metalad.aggregate.Aggregate:
        - class: Aggregate
        - load_error: None
        - module: datalad_metalad.aggregate
        - names:
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.conduct.Conduct:
        - class: Conduct
        - load_error: None
        - module: datalad_metalad.conduct
        - names:
          - meta-conduct
          - meta_conduct
      - datalad_metalad.dump.Dump:
        - class: Dump
        - load_error: None
        - module: datalad_metalad.dump
        - names:
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract:
        - class: Extract
        - load_error: None
        - module: datalad_metalad.extract
        - names:
          - meta-extract
          - meta_extract
    - load_error: None
    - module: datalad_metalad
    - version: 0.3.0a1+16.g75b77fc
```
